# Generated by Django 3.2.23 on 2024-05-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_auto_20240506_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=''),
        ),
    ]
