# Generated by Django 3.2.23 on 2024-05-15 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0004_alter_movie_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.CharField(choices=[('COM', 'Комедия'), ('ACT', 'Боевик'), ('THR', 'Триллер'), ('WES', 'Вестерн')], default='COM', max_length=3),
        ),
    ]
